README.md, rustsat/build.rs
=> Explain crates and installation

.github/workflows/rustsat.yml, rustsat/build.rs
=> Cbindgen fix

cadical/src/lib.rs, glucose/src/lib.rs, ipasir/src/lib.rs, kissat/src/lib.rs, minisat/src/lib.rs, pyapi/src/lib.rs, rustsat/src/encodings.rs, rustsat/src/encodings/card/dbtotalizer.rs, rustsat/src/encodings/card/totalizer.rs, rustsat/src/encodings/nodedb.rs, rustsat/src/encodings/pb.rs, rustsat/src/encodings/pb/dbgte.rs, rustsat/src/encodings/pb/dpw.rs, rustsat/src/encodings/pb/gte.rs, rustsat/src/instances/multiopt.rs, rustsat/src/instances/opt.rs, rustsat/src/instances/sat.rs, rustsat/src/lib.rs, rustsat/src/solvers.rs, rustsat/src/types.rs, rustsat/src/types/constraints.rs, tools/src/bin/shuffledimacs.rs
Add documentation missing for public elements.
=> Add missing documentation

solvertests/src/integration.rs
Check solutions for satisfiable instances in solver tests.
=> Check solutions in solver tests

capi/examples/Makefile, capi/src/lib.rs, rustsat/examples/Makefile
Forgot to move the Makefile for the examples before.
=> Cleanup C-API examples

.github/workflows/docs.yml, README.md, capi/README.md
The CI checks for whether the READMEs are up to date didn't work as expected.
=> Fix cargo rdme

.github/workflows/cadical.yml, .github/workflows/capi.yml, .github/workflows/docs.yml, .github/workflows/glucose.yml, .github/workflows/ipasir.yml, .github/workflows/kissat.yml, .github/workflows/minisat.yml, .github/workflows/pages.yml, .github/workflows/pr-lints.yml, .github/workflows/pyapi.yml, .github/workflows/rustsat.yml, .github/workflows/tools.yml, src/encodings.rs, src/encodings/card/dbtotalizer.rs, src/encodings/card/totalizer.rs, src/encodings/pb/dpw.rs, src/encodings/pb/gte.rs, src/utils.rs
Manually add `doc(cfg)` attributes to types that are only public with the `internals` feature.
=> Properly mark internals in documentation

cadical/Cargo.toml, cadical/build-all.sh, cadical/build.rs, cadical/patches/v211.patch, cadical/test-all.sh
Include CaDiCaL [Version 2.1.1](https://github.com/arminbiere/cadical/releases/tag/rel-2.1.1)
=> CaDiCaL Version 2.1.1

Cargo.lock, batsat/Cargo.toml, batsat/README.md, batsat/src/lib.rs
Update underlying `batsat` solver crate.
Closes #246
=> Update `batsat` to 0.6.0

Cargo.lock, Cargo.toml, src/instances.rs, src/instances/opt.rs, src/instances/sat.rs, tools/src/encodings/knapsack.rs
Update `rand` and `rand_chacha` to 0.9.0, with related code adjustments.
closes #250
closes #251
=> Update `rand` to 0.9.0

cadical/Cargo.toml, cadical/README.md, cadical/build-all.sh, cadical/build.rs, cadical/cppsrc/cadical_extension.hpp, cadical/cppsrc/ccadical_extension.cpp, cadical/cppsrc/ccadical_extension.h, cadical/cppsrc/solver_extension.cpp, cadical/patches/v213.patch, cadical/src/lib.rs, cadical/test-all.sh, solvertests/src/unit.rs
- Update CaDiCaL to [version 2.1.3](https://github.com/arminbiere/cadical/releases/tag/rel-2.1.3)
- Add support for CaDiCaL's new native implementation of `Propagate`
=> Update CaDiCaL to version 2.1.3

tests/opb.rs
This will enable #261 to pass the tests.
=> Simplify OPB tests

Cargo.lock, Cargo.toml, tools/Cargo.toml, tools/src/bin/enumerator.rs, tools/src/bin/gbmosplit.rs
- proper argument parser
- support opb input files
=> Improve enumerator tool

.config/abbreviations.dic, clippy.toml, src/encodings/am1/bitwise.rs, src/encodings/am1/ladder.rs
- fix `Ladder` reference venue
- fix `Bitwise` reference
=> Fix incorrect references for some encodings

Cargo.lock, pyapi/Cargo.toml
=> Update PyO3 to 0.24.0

src/instances/fio/dimacs.rs
=> fix: use var count from DIMACS header as minimum

flake.lock, flake.nix, renovate.json
=> chore: update devenv

.github/workflows/release-plz.yml, Cargo.toml, scripts/update-capi-header-version.sh
- update release-plz action
- update version in C-API header in release PR
- temporarily disable semver-checks lint
=> Update release-plz workflow

src/instances/fio/dimacs.rs, src/instances/fio/opb.rs, tools/src/bin/propagator.rs
- expose literal parsing functions as internals
- `propagator` tool
=> Propagator tool

.config/abbreviations.dic, Cargo.toml, README.md, src/lib.rs
=> docs: document MSRV policy

release-plz.toml, tools/Cargo.toml, tools/default.nix
=> chore(tools): version follows main crate

Cargo.toml, release-plz.toml
- add them back in as version dependencies so that example scraping on
docs.rs works
- publish main crate with `--no-verify`
=> fix: fix cyclic dev-dependencies

.github/workflows/ci.yml
=> chore(ci): build with all features

Cargo.lock, Cargo.toml, README.md, cadical/build.rs, glucose/build.rs, kissat/build.rs, minisat/build.rs, pigeons/Cargo.toml, src/instances/opt.rs, src/lib.rs, src/types.rs, src/types/constraints.rs, tools/Cargo.toml
=> feat: implement `pigeons` traits for types

README.md, batsat/README.md, cadical/README.md, capi/README.md, glucose/README.md, ipasir/README.md, kissat/README.md, minisat/README.md, pigeons/README.md, pyapi/README.md, src/lib.rs, tools/README.md
- **docs: document crates and features**
- **docs: update shield style**
=> feature docs

src/encodings/totdb.rs
With limited connections, input values to `GeneralNode::new` could be repeated, which lead to incorrect results of `vals` and failing debug assertions.
=> fix: GTE bug with limited connections

cadical/cpp-extension/ccadical_extension.cpp, cadical/src/prooftracer.rs
This slipped through the cracks of #340
=> fix: include `ctracer.cpp` in cadical build

.github/workflows/ci.yml
=> chore(ci): always run required check

README.md, batsat/README.md, cadical/README.md, glucose/README.md, ipasir/README.md, justfile, kissat/README.md, minisat/README.md, pigeons/README.md, pyapi/README.md, pyapi/pyproject.toml, tools/README.md
=> docs: update badges and docs link

.github/runner/Dockerfile, examples/profiling.rs, flake.lock, flake.nix, justfile, rust-toolchain.toml, src/instances/opt.rs, src/solvers/external.rs, tests/pb_encodings.rs, tools/src/bin/enumerator.rs, tools/src/bin/gbmosplit.rs
Make the default development toolchain pinned nightly.
Quite some of the dev tools required nightly already anyway.
=> chore: nightly development toolchain

batsat/src/lib.rs
- don't offset variables by one
- implement `reserve`
- track state and return state errors
=> Cleanup and improvements for Batsat

batsat/src/lib.rs, cadical/src/lib.rs, cadical/tests/internal_stats.rs, glucose/cppsrc/simp/SimpSolver.cc, glucose/src/core.rs, glucose/src/simp.rs, glucose/tests/incremental.rs, glucose/tests/internal_stats.rs, kissat/src/lib.rs, minisat/src/core.rs, minisat/src/simp.rs, minisat/tests/incremental.rs, minisat/tests/internal_stats.rs, solvertests/src/integration.rs, solvertests/src/lib.rs, solvertests/src/unit.rs
Various tests for uncovered functions.
Requires #379, #380, and #381 to be merged first.
=> test: increase test coverage for solvers

glucose/README.md, glucose/src/lib.rs, minisat/README.md, minisat/src/lib.rs, src/solvers.rs
=> docs: update minisat/glucose cpp source links

Cargo.toml
=> chore: format `Cargo.toml`

Cargo.lock, pyapi/Cargo.toml
=> chore(pyapi): update PyO3

.github/labeler.yml, .github/workflows/labeler.yml
=> chore(ci): add labeler action

renovate.json
=> chore(ci): disable lockfile maintenance

.config/nextest.toml, flake.lock, flake.nix
=> chore: update developement environment

pigeons/src/lib.rs
=> fix(pigeons): remove unnecessary space in rup without hints

justfile, src/solvers.rs, src/solvers/simulators.rs, tests/external_solver.rs, tests/solver_simulators.rs
=> feat(solvers): incremental solver simulator

.github/workflows/ci.yml, Cargo.lock, batsat/Cargo.toml, batsat/src/lib.rs, cadical/Cargo.toml, cadical/src/lib.rs, flake.nix, glucose/Cargo.toml, glucose/src/core.rs, glucose/src/simp.rs, ipasir/Cargo.toml, ipasir/src/lib.rs, kissat/Cargo.toml, kissat/src/lib.rs, minisat/Cargo.toml, minisat/src/core.rs, minisat/src/simp.rs, src/solvers/simulators.rs, src/utils.rs
- Abstract timer away
- Use `cpu_time::ThreadTime` instead of `cpu_time::ProcessTime`
- Use `std::time::Instant` on `wasm`
fixes #455
=> Timer abstraction

.github/workflows/release-plz.yml, flake.lock
=> chore(ci): update dev env and `release-plz` trusted publishing
