.github/workflows/check-test.yml, cadical/build.rs, glucose/build.rs, glucose/src/core.rs, glucose/src/simp.rs, kissat/build.rs, minisat/build.rs, minisat/src/core.rs, minisat/src/simp.rs
This is an attempt to fix [the issue I opened](https://github.com/chrjabs/rustsat/issues/46) for docs.rs build.
I kept it simple and just disabled the build of the C/C++ libraries when the doc is built.
Building the doc works locally, but I couldn't confirm it works on docs.rs.
=> Try to fix doc build on docs.rs

cadical/build.rs, glucose/build.rs, kissat/build.rs, minisat/build.rs, rustsat/Cargo.toml, rustsat/src/lib.rs
Disabling the library build with `cfg(not(doc))` seems to not be enough, disable it based on the `DOCS_RS` env var.
=> disable c++ library build on docs.rs

rustsat/Cargo.toml, rustsat/examples/print-lits.rs, rustsat/src/lib.rs, rustsat/src/types.rs
Enabling this feature changes the behaviour of the `Var` and `Lit` implementations of the `Display` trait to use IPASIR indexing
resolves #93
Without this feature enabled, the output of the new `print-lits` example is the following:
```
❯ cargo run --example=print-lits 2>/dev/null
`Display` IPASIR literal   1:               x0
`Display` IPASIR literal  -1:              ~x0
`Debug` IPASIR literal   1: Lit { lidx:  0 }
`Debug` IPASIR literal  -1: Lit { lidx:  1 }
`Display` IPASIR literal  42:              x41
`Display` IPASIR literal -42:             ~x41
`Debug` IPASIR literal  42: Lit { lidx: 82 }
`Debug` IPASIR literal -42: Lit { lidx: 83 }
```
With it enabled we get:
```
❯ cargo run --example=print-lits --features='ipasir-display' 2>/dev/null
`Display` IPASIR literal   1: …
```
=> `ipasir-display` feature

.github/workflows/cadical.yml, .github/workflows/glucose.yml, .github/workflows/ipasir.yml, .github/workflows/kissat.yml, .github/workflows/minisat.yml, .github/workflows/rustsat.yml, rustsat/src/encodings/card/dbtotalizer.rs, rustsat/src/encodings/pb/dbgte.rs, rustsat/src/encodings/pb/dpw.rs
The `Node` type internals were not supposed to be visible. This is technically a breaking change, but we will not treat it as such.
=> Make `Node` type opaque

.github/workflows/rustsat.yml, Cargo.toml, cadical/examples/cadical-cli.rs, kissat/examples/kissat-cli.rs, minisat/examples/minisat-cli.rs, solvertests/src/integration.rs, solvertests/src/lib.rs, src/encodings/am1.rs, src/encodings/card.rs, src/encodings/pb.rs, src/instances/fio.rs, src/instances/fio/dimacs.rs, src/instances/fio/opb.rs, src/instances/multiopt.rs, src/instances/opt.rs, src/instances/sat.rs, src/solvers.rs, src/solvers/external.rs, src/types.rs, tests/external_solver.rs, tools/src/bin/cnf2opb.rs, tools/src/bin/mcnf2opb.rs, tools/src/bin/opb2cnf.rs, tools/src/bin/opb2mcnf.rs, tools/src/bin/opb2wcnf.rs, tools/src/bin/wcnf2opb.rs
Interface for calling external solver binaries. The input instance can be either passed via a pipe to stdin, via a temporary file, or via a persistent file. Output can be be processed either via a pipe or via a persistent file.
=> External solvers

src/types.rs
Since Rust performs overflow checks on integers in debug builds by default, users might expect that they would be performed on custom types as well.
Since the `Var` type is only allowed to take values up to `(u32::MAX - 1) / 2`, the default runtime checks do _not_ capture "overflows" on this type.
=> Check variable addition overflow in debug builds

.github/workflows/capi.yml, .github/workflows/release.yml, Cargo.toml, batsat/Cargo.toml, cadical/Cargo.toml, flake.lock, flake.nix, glucose/Cargo.toml, kissat/Cargo.toml, minisat/Cargo.toml, scripts/dry-run-publish.sh, shell.nix, tools/Cargo.toml
reduces published package sizes:
- `rustsat`: 7.3MiB -> 921.3KiB
- `rustsat-batsat`: 6.5MiB -> 9.1KiB
- `rustsat-cadical`: 6.6MiB -> 120.5KiB
- `rustsat-glucose`: 7.1MiB -> 508.6KiB
- `rustsat-kissat`: 8.8MiB -> 1.2MiB
- `rustsat-minisat`: 6.8MiB -> 272.0KiB
- `rustsat-tools`: 6.7MiB -> 165.9KiB
runs `cargo publish --dry-run` on PRs
=> Shrink releases and test publish on PRs

.github/workflows/pyapi.yml, pyapi/pyproject.toml, pyapi/python/rustsat/__init__.pyi, pyapi/python/rustsat/encodings/__init__.pyi, pyapi/python/rustsat/encodings/am1/__init__.pyi, pyapi/python/rustsat/encodings/card/__init__.pyi, pyapi/python/rustsat/encodings/pb/__init__.pyi
Fixes failing checks in #216 (and includes it), as well as another small issue with the newest `maturin`.
- **fix(pyapi): stricter `pyproject.toml` requirements**
- **fix(pyapi): specify `__all__` in python stubs**
- **chore(deps): update install-pinned/mypy digest to 75779f1**
=> Fix Py-API checks with newer `maturin` and `mypy`

capi/Cargo.toml, pyapi/Cargo.toml
Enable the `fxhash` feature for the C-API and Python-API crates.
This does not only speed up hashed datastructures but also guarantee that they are deterministic.
=> Use fxhash in C-API and Python-API

src/encodings/pb/dpw.rs
If the encoding has a single input, don't build an encoding structure
when reserving variables, since the input can be used to enforce
bounds
=> DPW reserve bug

pyapi/python/rustsat/encodings/am1/__init__.pyi, pyapi/src/encodings/am1.rs, pyapi/src/lib.rs
Include the Bimander AM1 encoding in the Python API
=> Bimander encoding for Python API

.github/workflows/capi.yml, .github/workflows/pyapi.yml, Cargo.toml, capi/Cargo.toml, pyapi/Cargo.toml, scripts/sync-versions.sh
Rather than manually syncing the versions for the main crate and the C/Python-API, set the version in the cargo workspace.
=> Force synced versions via workspace

capi/cbindgen.toml, capi/rustsat.h, capi/src/encodings.rs, capi/src/encodings/adder.rs, capi/src/encodings/bimander.rs, capi/src/encodings/bitwise.rs, capi/src/encodings/commander.rs, capi/src/encodings/commander.rs~, capi/src/encodings/dpw.rs, capi/src/encodings/gte.rs, capi/src/encodings/ladder.rs, capi/src/encodings/pairwise.rs, capi/src/encodings/totalizer.rs, src/encodings/am1/bimander.rs, src/encodings/am1/bitwise.rs, src/encodings/am1/commander.rs, src/encodings/am1/ladder.rs, src/encodings/am1/pairwise.rs, src/encodings/card/dbtotalizer.rs, src/encodings/pb/dpw.rs
- don't sort functions
- cleanup
- basic tests for am1 encodings
- include at-most-one encodings
- clippy
=> Extend C-API

src/bench.rs, src/encodings/card/dbtotalizer.rs, src/encodings/pb/dbgte.rs
Optimize some code in the creation of the tree structure in `DbGte`.
Not does not use a `BTreeMap` anymore, but a manually maintained sorted vector.
Lookups are done with `slice::binary_search`.
Where the old (`GeneralizedTotalizer`) implementation was previously quite a
bit faster, for many inputs (here 100), the new (`DbGte`) implementation is now
faster.
For less inputs (50), the old implementation is still faster.
Also, when not encoding the entire tree, the old implementation tends to be
faster, since the new implementation computes all possible subsum values at
initialization, while the old one only does so when they are needed.
**Before** (at 3648bec)
```
test bench::pb_enc::dbgte_ub         ... bench:  88,486,775.90 ns/iter (+/- 20,036,162.14)
test bench::pb_enc::dbgte_ub_large …
```
=> Optimize `DbGte`

src/encodings/pb/adder.rs, tests/pb_encodings.rs
=> fix: two bugs in `BinaryAdder`

src/encodings.rs, src/encodings/card.rs, src/encodings/card/dbtotalizer.rs, src/encodings/card/simulators.rs, src/encodings/card/totalizer.rs, src/encodings/nodedb.rs, src/encodings/pb.rs, src/encodings/pb/adder.rs, src/encodings/pb/dbgte.rs, src/encodings/pb/dpw.rs, src/encodings/pb/simulators.rs, src/encodings/totdb.rs, tests/card_encodings.rs, tests/pb_encodings.rs
First batch of the many changes in #248
- refactor!: move totalizer database to separate module
- perf!: remove blanket implementations for both bounding encodings
=> refactor for proof logging

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, README.md, cadical/build.rs, glucose/build.rs, kissat/build.rs, minisat/build.rs, pigeons/Cargo.toml, src/encodings/atomics.rs, src/encodings/card.rs, src/encodings/pb.rs, src/instances.rs, src/instances/opt.rs, src/lib.rs, src/solvers.rs, src/types.rs, src/types/constraints.rs, tests/card_encodings.rs, tests/external_solver.rs, tools/Cargo.toml
Random things from #248
- feat!: more functionality on constraint types
- feat: reified cardinality/PB encodings in `atomics`
- tests: more tests for `DbTotalizer`
- tests: formatting in external solver tests
- docs: copy past typos in encoding traits
- fix: `ReindexingVarManager` map with identity with initialized with next free
- feat: `Initialize` trait
=> functionality and cleanup

capi/Cargo.toml, codegen/Cargo.toml, pyapi/Cargo.toml, release-plz.toml, solvertests/Cargo.toml
Rather than adding crates that shouldn't be published to
`release-plz.toml` one by one, add `publish = false` to their respective
`Cargo.toml`
=> chore: add `publish = false` where appropriate

src/encodings/totdb.rs
=> fix: always cache node values in `ValueIter`

Cargo.lock, Cargo.toml
Re-enables the `runtime` feature flag for `bindgen`, should fix #367.
=> Re-enable runtime feature flag for bindgen

minisat/build.rs, minisat/cppsrc/minisat/cminisat.cc, minisat/cppsrc/minisat/cminisat.h, minisat/cppsrc/minisat/core/Solver.cc, minisat/cppsrc/minisat/core/Solver.h, minisat/cppsrc/minisat/mtl/Vec.h, minisat/src/core.rs, minisat/src/lib.rs, minisat/src/simp.rs
- don't convert to IPASIR literals
- pass slices between Rust and C
- makes wrapper type in C-API obsolete
- implement `reserve`
see #380 for the equivalent for Glucose
=> refactor(minisat): rework C-API

glucose/build.rs, glucose/cppsrc/cglucose4.cc, glucose/cppsrc/cglucose4.h, glucose/cppsrc/core/Solver.cc, glucose/cppsrc/core/Solver.h, glucose/cppsrc/mtl/Vec.h, glucose/src/core.rs, glucose/src/lib.rs, glucose/src/simp.rs
- don't convert to IPASIR literals
- pass slices between Rust and C
- makes wrapper type in C-API obsolete
- implement `reserve`
see #379 for the equivalent for Minisat
=> refactor(glucose): rework C-API

glucose/cppsrc/simp/SimpSolver.cc, glucose/src/simp.rs
Undefined behaviour in glucose due to invalid memory accesses and uninitialized memory.
Observed first in windows tests in #382
=> Glucose fix undefined behaviour
